language: java

os: linux

env:
  global:
    - SQOOP_SERVER_ADDRESS=http://192.168.11.25:12000/sqoop/

sudo: required

jdk:
  - oraclejdk8

script: mvn clean install cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)